version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk17
branches:
  only:
    - develop
    - support/4.1.x
    - support/4.0.x
    - master
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "tRivQ2X8cHsMUNk+B6UCyEuI0OEBuZevySCxN5BURY6i47JmxKIUBIIZDhOSkH7/UHBxlC125zPaq1xE/N1SQcv9MiWCZuLtSTrGkjx5SstOAwchTLMvzbDX72ZiHaomSG+D0Mg3qrvBPEknsegzr43sSsLtMYEZvkSBHptaUaU="
    - secure: "A18qXNEqzGXmrbLaP/slKhwpVIRFnDdFCcgTpKj3qg78NeSN2L25MEqXOVLTFI8Nxmh7In6ChbQOrw4S21lrNl2M5BtKMkzdSExAoalTDVCzokltRRrDNrw0zPRKZW5UkWxysCDmDb0MUDTzNX1L07fb9MQclVyPB8LHPUGaa5c="
